services:
  db:
    image: postgres:15
    container_name: seletivo-db
    environment:
      POSTGRES_DB: seletivo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - seletivo-net

  minio:
    image: minio/minio
    container_name: seletivo-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - seletivo-net

  api:
    build: ./api
    container_name: seletivo-api
    depends_on:
      - db
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seletivo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      MINIO_INTERNAL_HOST: ${MINIO_INTERNAL_HOST:-minio}
      MINIO_INTERNAL_PORT: ${MINIO_INTERNAL_PORT:-9000}
      MINIO_PUBLIC_HOST: ${MINIO_PUBLIC_HOST:-localhost}
      MINIO_PUBLIC_PORT: ${MINIO_PUBLIC_PORT:-9000}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    ports:
      - "8080:8080"
    networks:
      - seletivo-net

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${API_PUBLIC_URL}
    container_name: seletivo-frontend
    depends_on:
      - api
    environment:
      - NODE_ENV=production
    ports:
      - "5173:5173"
    networks:
      - seletivo-net

volumes:
  db_data:
  minio_data:

networks:
  seletivo-net:
    driver: bridge
